from fastapi import Depends
from sqlalchemy.orm import Session
from services.ingest.app import app, get_db
from services.ingest.db import NewsItem
from services.ranker import rank_items

# Re-export the app for compatibility with uvicorn main:app
__all__ = ["app"]

def get_ranked_news(db: Session, limit: int):
    recent_items = db.query(NewsItem).filter(NewsItem.is_recent).all()
    ranked = rank_items(recent_items)
    return ranked[:limit]

@app.get("/ranked-news")
def ranked_news(limit: int = 10, db: Session = Depends(get_db)):
    items = get_ranked_news(db, limit=limit)
    return [{"id": i.id, "title": i.title, "url": i.url, "score": i.popularity} for i in items]

@app.get("/ranked-news-with-summary")
def ranked_news_with_summary(limit: int = 10, db: Session = Depends(get_db)):
    """
    Returns top N ranked news items with their summaries.
    Each item includes a short 50-120 character teaser generated by the summarizer.
    """
    items = get_ranked_news(db, limit=limit)
    return [
        {
            "id": i.id,
            "title": i.title,
            "url": i.url,
            "score": i.popularity,
            "summary": i.summary,
            "source": i.source,
            "published_at": i.published_at,
            "fetched_at": i.fetched_at
        }
        for i in items
    ]
